In [2]:
print("hi")

hi


In [4]:
#IMPORT LIBRARIES 
import numpy as np

In [5]:
my_random_array = np.random.randn(2, 3)
my_random_array

array([[ 0.48322278, -0.14066421, -0.1235064 ],
       [-0.22258093, -0.72688176, -1.42178914]])

In [8]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive 

array([1, 2, 3, 4])

In [ ]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

In [9]:
bigMatrix = np.random.randn(10, 5)
print(bigMatrix)

[[-0.19026931 -0.06664079 -0.96786549 -0.32462022 -0.99530671]
 [-0.48037466  0.67577635  0.59357225 -0.40312255 -1.25179999]
 [ 0.81124283  0.06956465 -0.14493777 -1.0982683  -0.35071252]
 [-0.41433827 -0.56410656  0.37827059  1.88408839 -0.5288418 ]
 [-1.23018767 -0.22276928 -0.75428139  0.36251111  0.65324482]
 [ 0.14274386 -0.36388903  0.25576997 -0.30279683  1.82500921]
 [-0.81555101  1.10742496  2.10877593  0.96145397 -0.9133552 ]
 [-0.71040897 -0.69544479  1.12859518 -0.51468124  0.25735082]
 [-0.3876482  -0.08136265  0.29094676 -0.17348919 -1.76903102]
 [ 0.58928713 -1.03764347  0.37419674 -0.2920712  -0.91633262]]


In [10]:
bigMatrix.shape

(10, 5)